# Generated by Django 4.2.5 on 2023-10-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='cat',
        ),
    ]
