# Generated by Django 4.2.5 on 2023-10-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_rename_category_photo_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['time_created']},
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
