# Generated by Django 4.2.5 on 2023-10-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_photo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
