# Generated by Django 4.2.5 on 2023-12-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_remove_photo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='time_updated',
        ),
        migrations.AlterField(
            model_name='photo',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации фотосъемки'),
        ),
    ]
